---

- name: Install tools to create and configure the bridge and provide dhcp to the containers
  shell: apt-get --yes --allow-unauthenticated install bridge-utils dnsmasq-base

# not allowed to do this even when running as root
#- name: Turn on forwarding to support NAT
#  lineinfile:
#    dest: /proc/sys/net/ipv4/ip_forward
#    line: "1"

- name: Turn on forwarding to support NAT
  lineinfile:
    dest: /etc/sysctl.conf
    line: "net.ipv4.ip_forward=1"

- name: Create network bridge
  blockinfile:
    dest: /etc/network/interfaces
    block: |
      auto lxcbr0
      iface lxcbr0 inet static
        address 192.168.30.1
        netmask 255.255.255.0
        post-up /opt/bin/lxcbr0-up

- name: Make directory for bridge post-up script
  file: path=/opt/bin state=directory

- name: Write bridge post-up script
  blockinfile:
    create: yes
    dest: /opt/bin/lxcbr0
    mode: ugo+x
    block: |
      #!/bin/sh
      # This is the address we assigned to our bridge in /etc/network/interfaces
      braddr=192.168.30.1
      # ip address range for containers
      brrange=192.168.30.2,192.168.30.254
      iptables -A FORWARD -i lxcbr0 -s ${braddr}/24 -m conntrack --ctstate NEW -j ACCEPT
      iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
      iptables -A POSTROUTING -t nat -j MASQUERADE
      dnsmasq --bind-interfaces --conf-file= --listen-address $braddr --except-interface lo --dhcp-range $brrange --dhcp-lease-max=253 --dhcp-no-override

- name: Bring up the bridge
  shell: ifup lxcbr0
