---

- name: Apt-get update
  apt:
    update_cache: yes

# Workaround for apt-get issue described here:
# https://github.com/ansible/ansible/issues/27401
# Workaround can be replaced by using the force_apt_get flag after updating to ansible 2.4
- name: Prevent bug with apt-get upgrade
  shell: dpkg --configure -a

- name: Apt-get upgrade
  shell: PT_LISTCHANGES_FRONTEND=none DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get upgrade -f -y --force-yes -oDpkg::Options::="--force-confdef" -oDpkg::Options::="--force-confold"
#  apt:
#    upgrade: yes
#    force_apt_get: yes

- name: Get distribution upgrade
  apt:
    upgrade: dist

- name: Update sources.list to include new Stretch repositories
  command: sed -i 's/jessie/stretch/g' /etc/apt/sources.list

- name: Apt-get update
  apt:
    update_cache: yes

- name: Apt-get upgrade
  command: env APT_LISTCHANGES_FRONTEND=none DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get upgrade -y --force-yes -oDpkg::Options::="--force-confdef" -oDpkg::Options::="--force-confold"
#  apt:
#    upgrade: yes
#    force_apt_get: yes

- name: Get distribution upgrade
  apt:
    upgrade: dist
