---
- include_vars: ../../common/vars/vault.yml

- name: Upgrade to latest Debian
  include: debian.yml
  when: ansible_distribution == "Debian" and not ansible_distribution_major_version == "9"

- name: Install debootstrap
  apt:
    name: debootstrap

#- name: Install qemu
#  apt:
#    name: qemu

#- name: Install qemu-user-static
#  apt:
#    name: qemu-user-static

#- name: Install binfmt-support
#  apt:
#    name: binfmt-support

- name: Install lxc
  apt:
    name: lxc

- name: Touch container directory
  file: path=/var/lib/lxc/container state=directory

- name: Transfer container system
  synchronize: src=../rootfs dest=/var/lib/lxc/container/

#- name: Copy qemu files for compiling
#  copy:
#    src: /usr/bin/qemu-arm-static
#    dest: /var/lib/lxc/container/rootfs/usr/bin
#    remote_src: yes

- name: Run debootstrap second stage
  command: chroot /var/lib/lxc/container/rootfs /debootstrap/debootstrap --second-stage

- name: Set container password
  command: chroot /var/lib/lxc/container/rootfs echo 'root:{{ root_pass }}'|chpasswd

- name: Configure the container, include settings for bridge
  blockinfile:
    dest: /var/lib/lxc/container/config
    create: yes
    block: |
      lxc.utsname = container
      lxc.rootfs = /var/lib/lxc/container/rootfs
      lxc.start.auto = 1
      lxc.start.delay = 5
      lxc.network.type = veth
      lxc.network.flags = up
      lxc.network.link = lxcbr0
      lxc.network.name = wlan0
      lxc.network.ipv4 = 192.168.30.2
      lxc.network.ipv4.gateway = 192.168.30.1

- name: Set up network bridge for container
  include: bridge.yml

- name: Start container
  command: lxc-start -n container
